server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5450/postgres
    username: user_service
    password: user_service
    hikari:
      schema: users
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml