server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5450/postgres
    username: user_service
    password: user_service
    hikari:
      schema: users

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/electronics-store

springdoc:
  api-docs:
    path: /user-service/v3/api-docs
  swagger-ui:
    path: /user-service/swagger-ui.html

logging:
  level:
    org:
      zalando:
        logbook:
          Logbook: TRACE